apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaccion
  namespace: elvale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaccion
  template:
    metadata:
      labels:
        app: transaccion
    spec:
      containers:
        - name: transaccion
          image: elturcofarid/transaccion_elvale:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: transaccion
  namespace: elvale
spec:
  #type: LoadBalancer
  selector:
    app: transaccion
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 80
